# NumPy Tutorial
### Author: Ally Chen



## Description
### What is NumPy?
NumPy is Python's standard library for working with arrays. It supports working with arrays of N-dimensions, which is a principle of NumPy. Instead of looping in Python, NumPy lets you perform fast math on whole arrays at once, known as vectorized operations. Most data libraries (pandas, SciPy, scikit-learn, PyTorch) rely on NumPy under the hood.

## NumPy Installation
1. Open a new terminal
2. Ensure Python is installed:
 - Check using 'python --version' in terminal
3. In terminal run:
 - macOS/Linux
python3 -m venv .venv
source .venv/bin/activate
python -m pip install --upgrade pip
pip install numpy
 - Windows (PowerShell)
python -m venv .venv
.venv\Scripts\Activate
python -m pip install --upgrade pip
pip install numpy

## Verify Installation
Copy and paste the following code into your preferred code editor, and run it in the terminal to test if it is installed correctly.

In [92]:
# Import Numpy library
import numpy as np

# Print NumPy version number
print("NumPy:", np.__version__)

# Expected output: 25
print (np.array([3,4]).dot([3,4]))

NumPy: 2.3.2
25


# Part 1: Arrays

# Multi-Dimensional Arrays

### **What is a Multi-Dimensional Array?**
Multi-dimensional arrays are the backbone of NumPy.

- A 1D array is like a simple list `[1, 2, 3]`.
- A 2D array is like a table or matrix (rows × columns).
- A 3D array is like a stack of tables.
- Higher dimensions are possible, but most people stop at 2D or 3D for practical work.

*NumPy arrays are called ndarrays (“n-dimensional arrays”) because they can have any number of dimensions.*

The more dimensions an array has, the trickier they are to understand. 
**Lets look at some examples to understand better:**

**2D array**

In [93]:
# 2D array (matrix)
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# This is a 2D array, with 2 rows and 3 columns.
print(A.shape) # (2, 3)

(2, 3)


**3D array**
Think of a 3D array as a stack of 2D tables (matrices).
- Each table has rows and columns (2D)
- When you stack multiple tables on top of eachother, another dimension is added &rarr; ***depth***.

Simply put, a 3D array is like a cube of numbers.

In [94]:
# A 3D array: 2 "tables", each with 3 rows and 4 columns.
arr = np.array([
    # Table 1
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]],

    # Table 2
    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


When these two tables are stacked together, they form a 3D block of numbers.

**How do we read the shape of a 3D array?**

In [95]:
print(arr.shape) # (2, 3, 4)

(2, 3, 4)


In this 3D array:
- 2 &rarr; shows the number of "tables" (or layers in the stack).
- 3 &rarr; shows the number of rows in each table.
- 4 &rarr; shows the number of columns in each table.

### **Exercise:** Work with Multi-Dimensional Arrays

Try it out! For this exercise you will get some practice creating arrays with different dimensions. Complete the following using the starter code:
1. Create a 1D array of number from 7-12.
2. Create a 2D array with 3 rows × 2 cols using these rows: `[10, 20], [30, 40], [50, 60]`.
3. Create a 3D array with 2 layers, each layer is 2×3:
   
layer 0 → `[[100, 101, 102], [103, 104, 105]]`

layer 1 → `[[200, 201, 202], [203, 204, 205]]`

4. For each array, print the array, the number of dimensions (`.ndim`), and the shape (`.shape`).

In [96]:
# Starter Code

import numpy as np

# 1) 1D: 7–12
a1 = __
print("1D:\n",__,"\nndim:",__,"\nshape:",__)

# 2) 2D: 3x2 table
a2 = __
print("\n2D:\n",__,"\nndim:",__,"\nshape:",__)

# 3) 3D: 2 layers, each 2x3
a3 = __
print("\n3D:\n",__,"\nndim:",__,"\nshape:",__)

1D:
  
ndim:  
shape: 

2D:
  
ndim:  
shape: 

3D:
  
ndim:  
shape: 


### **SOLUTION**

#### ***PAUSE HERE.*** 
Try filling in the blanks yourself before scrolling down.

In [97]:
import numpy as np

# 1) 1D: 7–12
a1 = np.array([7, 8, 9, 10, 11, 12])
print("1D:\n", a1,"\nndim:", a1.ndim,"\nshape:", a1.shape)

# 2) 2D: 3x2 table
a2 = np.array([
    [10, 20],
    [30, 40],
    [50, 60],
])
print("\n2D:\n", a2,"\nndim:", a2.ndim,"\nshape:", a2.shape)

# 3) 3D: 2 layers, each 2x3
a3 = np.array([
    [[100, 101, 102], [103, 104, 105]],
    [[200, 201, 202], [203, 204, 205]],
])
print("\n3D:\n", a3,"\nndim:", a3.ndim,"\nshape:", a3.shape)

1D:
 [ 7  8  9 10 11 12] 
ndim: 1 
shape: (6,)

2D:
 [[10 20]
 [30 40]
 [50 60]] 
ndim: 2 
shape: (3, 2)

3D:
 [[[100 101 102]
  [103 104 105]]

 [[200 201 202]
  [203 204 205]]] 
ndim: 3 
shape: (2, 2, 3)


## **Other Arrays:**
Apart from multi-dimensional arrays, NumPy lets you create arrays in many other ways. Here's some of the most common ones:
- `np.array([...])`
- `np.zeros()` / `np.ones()`
- `np.full()`
- `np.arange(start, stop, step)`
- `np.linspace(start, stop, num)`

#### **np.array()**
This array is from the Python list; we've seen this used previously when learning multi-dimensional arrays. 
- Each pair of brackets `[...]` adds a new dimension.
- So a 1D list is a vector, a list of lists is a 2D matrix, a list of lists of lists is 3D, and so on.

`np.array()` can create arrays of any number of dimensions, depending on the structure of the input you give it. 

Heres how:

In [98]:
# 1D
a = np.array([1, 2, 3])

# 2D
b = np.array([[1, 2, 3],
              [4, 5, 6]])

# 3D
c = np.array([ [[1, 2], [3, 4]],
               [[5, 6], [7, 8]] ])

#### **np.zeros() / np.ones()**
These two arrays are super useful for quickly creating arrays filled with zeros or ones of any shape you want.

- `np.zeros` create an array where every element is 0.
- `np.ones` creates an array where every element is 1.
- Both let you quickly generate arrays of any size or any dimension.


***Why are these useful?***
1. They're useful as placeholders or starting points when you know the shape of the data but don’t yet have values to fill in.
2. Testing & Prototyping: You can make arrays quickly to test functions without worrying about real data.
*Example: creating a 10×10 grid of zeros to test matrix operations.*
3. Machine Learning / Math: You often initialize weights or matrices with zeros or ones.
4. Consistency: Sometimes you need a clean “all-zero” baseline to compare against another array.

***How do we create these arrays?***

Lets start with `np.zeros()`:

The structure for this is `np.zeros(shape)`, where `shape` is the dimensions of the array you want NumPy to build.

In [99]:
# 1D array of 5 zeros
a = np.zeros(5) 

# 2D array (2 rows, 3 columns)
b = np.zeros((2, 3))   

# 3D array (2 tables, 2 rows, 2 columns)
c = np.zeros((2, 2, 2))

print("a:\n", a)
print("b:\n", b)
print("c:\n", c)

a:
 [0. 0. 0. 0. 0.]
b:
 [[0. 0. 0.]
 [0. 0. 0.]]
c:
 [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


**Next:**

`np.ones(shape)` is the same thing, but filled with ones instead:

In [100]:
# 1D array of 5 ones
a = np.ones(5) 

# 2D array (2 rows, 3 columns)
b = np.ones((2, 3))   

# 3D array (2 tables, 2 rows, 2 columns)
c = np.ones((2, 2, 2))

print("a:\n", a)
print("b:\n", b)
print("c:\n", c)

a:
 [1. 1. 1. 1. 1.]
b:
 [[1. 1. 1.]
 [1. 1. 1.]]
c:
 [[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


***Is the possible to make an array full of a number besides ones and zeros?***

The answer is **yes!** For that we use:

#### **np.full()**
This creates an array of the given shape, filled with whatever value you choose. Using it is the same as creating an array of ones or zeros, but the structure is slightly different.
- `np.full(shape, fill_value)` where fill_value represents any constant value you fill the array with.
- It works just like `np.zeros/np.ones` but more flexible.


In [101]:
# A 2x3 array filled with 7
a = np.full((2, 3), 7)

# A 3D array (2x2x2) filled with -1
b = np.full((2, 2, 2), -1)

print("a:\n", a)
print("b:\n", b)

a:
 [[7 7 7]
 [7 7 7]]
b:
 [[[-1 -1]
  [-1 -1]]

 [[-1 -1]
  [-1 -1]]]


### **Mini-Exercise:** Creating Constant Number Arrays

For this mini exercise, you are tasked with the following:
1. Create a `5x5` array of all zeros.
2. Create a `2x3` array of all ones.
3. Create a `2x2x2` array filled with 5.
4. Print each array and its `.shape` to confirm its dimensions.

Use the starter code provided below:

In [ ]:
# Starter Code

import numpy as np

# 1. Create a 5x5 array of zeros
a = ___

# 2. Create a 2x3 array of ones
b = ___

# 3. Create a 2x2x2 array filled with 5
c = ___

# Print arrays and their shapes
print("a:\n", a)
print("Shape of a:", a.shape)

print("\nb:\n", b)
print("Shape of b:", b.shape)

print("\nc:\n", c)
print("Shape of c:", c.shape)


**SOLUTION**

***Pause here and try it yourself before scrolling down.***

In [ ]:
a = np.zeros((5, 5))
b = np.ones((2, 3))
c = np.full((2, 2, 2), 5)

print("a:\n", a)
print("Shape of a:", a.shape)

print("\nb:\n", b)
print("Shape of b:", b.shape)

print("\nc:\n", c)
print("Shape of c:", c.shape)


Now lets move onto creating sequences!

#### **np.arange()**
NumPy’s `np.arange(start, stop, step)` works like Python’s built-in range(), but it creates a NumPy array instead of a list.
- `start` &rarr; where the sequence begins (default = 0).
- `stop` &rarr; where the sequence ends (no default).
- `step` &rarr; how much to increase each time (default = 1).

***Why is this useful?***
1. Quick Sequences: It’s the fastest way to make arrays of consecutive numbers or evenly spaced numbers without typing them out manually.
2. Works with Any Step Size: You can make arrays that skip numbers (like evens, odds, multiples of 3, etc.) or even count backwards.
3. Great for Reshaping: Later in the tutorial, when you learn `.reshape()`, `arange` is super handy. You can generate a block of numbers and then reshape it into a 2D or 3D array.\

***Let's see what this array can do!***

In [ ]:
# Sequence:
# 0 up to (but not including) 100.
a = np.arange(0, 100)  

# Sequence by any step size:
# Start = 0, stop = 15 (ends at 12), step = 3.
b = np.arange(0, 15, 3)  

# Counting down:
# De-increment by 1.
c = np.arange(5, -5, -1)

# Counting up by even numbers:
# Start = 2, end = 13 (ends at 12), step = 2.
d = np.arange(2, 13, 2)

print("a:", a)
print("b:", b)
print("c:", c)
print("d:", d)

*Reminder:* Arrays start from 0, meaning the elements in the array will always be n-1.

### **Mini-Exercise:** Creating Sequences

Your turn! Let's get some practice with creating sequencing arrays. Complete the following using the provided starter code:
1. Create an array of numbers from 0 to 20 (not including 20).
2. Create an array of odd numbers from 1 to 19.
3. Create an array that counts down from 10 to 1.

In [ ]:
import numpy as np

# 1. Numbers from 0 to 19
a = np.arange(__)
print("a:", a)

# 2. Odd numbers from 1 to 19
b = np.arange(__)
print("b:", b)

# 3. Countdown from 10 to 1
c = np.arange(__)
print("c:", c)


**SOLUTION**

***Pause here and try it yourself before scrolling down.***

In [ ]:
import numpy as np

# 1. Numbers from 0 to 19
a = np.arange(0, 20)
print("a:", a)

# 2. Odd numbers from 1 to 19
b = np.arange(1, 20, 2)
print("b:", b)

# 3. Countdown from 10 to 1
c = np.arange(10, 0, -1)
print("c:", c)


**Last on the list we have:**

**np.linspace()**

While `np.arange()` creates arrays based on a step size,
`np.linspace()` creates arrays based on a number of evenly spaced points between two values.
You tell it:
- Where to start (the beginning of the line)
- Where to stop (the end of the line)
- How many pieces you want in between

Then it gives you all the marks where it's split.

**To help visualize:**
- You have a tine that goes from 0 to 10.
- You tell NumPy to divide it into 5 equal parts," it will place marks at equal spacing.
  
So the marks land at:

Those marks are the numbers that linspace gives you.

**Here's the example in NumPy terms:**

In [ ]:
# Split the line from 0 to 10 into 5 equal parts
# This array starts at 0, stops at 10, and has 5 pieces.

arr = np.linspace(0, 10, 5)
print(arr)


***Why is this useful?***
1. Even spacing: If you need exactly 50 values between 0 and 1, linspace does it automatically.
2. Works with floats: Unlike arange, which might have rounding issues, linspace is great for decimals.
3. Used in plotting: Very common in math/engineering/CS when you need smooth ranges for graphs.

***When should you use `.arange` vs `linspace`?***
- Use `.arange` when you know the **step size** you want.
- Use `.linspace` when you know the **number of points** you want.

Here's a side-by-side example:

In [ ]:
# arange: fixed step
a = np.arange(0, 11, 2)   # from 0 to 10, step of 2
print("arange:", a)

# linspace: fixed number of points
b = np.linspace(0, 10, 6) # 6 points between 0 and 10
print("linspace:", b)


Notice how both cover the same range, but:
- `.arange` does it by stepping by 2

- `.linspace` does it by saying “give me 6 points, evenly spaced”

### **Mini-Exercise:** Cutting the line

Task: 
1. Use np.linspace() to create 7 evenly spaced numbers between 0 and 21.
2. Print the array, its shape, and size to inspect it.

The starter code is provided below:

In [ ]:
# Starter Code

import numpy as np

# 1. Create a linspace array
arr = np.linspace(__)

# 2. Print array
print("Array:", __)

# 3. Inspect the array
print("Shape:", __)  # dimensions of the array
print("Size:", __)    # total number of elements


**SOLUTION**

***Pause here and try it yourself before scrolling down.***

In [ ]:
import numpy as np

# 1. Create linspace array
arr = np.linspace(0, 21, 7)

# 2. Print array
print("Array:", arr)

# 3. Inspect the array
print("Shape:", arr.shape)  # dimensions of the array
print("Size:", arr.size)    # total number of elements


### Inspecting Arrays

This section will look at the metadata of an array (not just the numbers inside it). That way, when working with bigger data later, you know how to read and deal with the information.

**When you create arrays, its important to know:**
- `.shape` &rarr; the size in each dimension (rows, cols, …)
- `.ndim` &rarr; number of dimensions (1D vector, 2D matrix, etc.)
- `.size` &rarr; total number of elements in array,
- `.dtype` &rarr; type of values inside the array (integers, floats, etc.)

***Why is `Shape` important?***

The `shape` attribute shows the structure of an array, meaning how many rows, columns, or higher dimensions it has. This is important because NumPy operations often require arrays to have matching or compatible shapes. Most NumPy errors come from shape mismatches.

In [ ]:
import numpy as np

# 2 rows, 3 columns
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)   # (2, 3)

***Why is `Size` important?***

The `size` attribute tells you the total number of elements inside the array. This is useful for double-checking that you created the expected amount of data and for estimating how much memory the array might use.

In [ ]:
# total of 6 elements
print(arr.size)   # 6

***Why is `ndim` important?***

The `ndim` attribute shows how many dimensions the array has. For example, a one-dimensional array looks like a list, a two-dimensional array looks like a table, and a three-dimensional array can be thought of as a stack of tables. Knowing the number of dimensions helps you understand the structure of your data.

In [ ]:
# this is a 2D array
print(arr.ndim)   # 2

***Why is `dtype` important?***

The `dtype` attribute tells you what kind of values are stored in the array, such as integers, floating-point numbers, or booleans. This matters because it determines the precision of calculations and whether certain operations can be carried out without errors.

In [ ]:
print(arr.dtype)   # int64

### **Exercise:** Building Arrays from Scratch

Congratulations, you've completed Part 1: Arrays! This is a big milestone because arrays are the foundation of NumPy. If you understand arrays, everything else, indexing, slicing, broadcasting, and reshaping, will make much more sense later. 

So far, you’ve been working with guided examples and starter code. This time, you’re upgrading! No starter code is provided. Instead, you’ll need to apply everything you’ve learned about arrays:
- Creating arrays with `np.array`, `np.zeros`, `np.ones`, `np.fill`, `np.arange`, and `np.linspace`.
- Understanding dimensions, including multi-dimensional arrays (2D, 3D, and beyond).
- Inspecting arrays.

Feel free to refer to the tutorial examples if you're stuck!

***Task:***
1) Multi-dimensional &rarr; Create a 3D array with shape (2, 3, 4) filled with any numbers.

2) Zeros and ones &rarr; Create a 2D array of shape (4, 4) filled with zeros, and a 2D array of shape (3, 5) filled with ones.

3) Custom fill &rarr; Create a 3D array of shape (2, 2, 2) filled with the number 7.

4) Ranges &rarr; Use np.arange to generate a sequence from 5 to 30 with a step of 5.

5) Even spacing &rarr; Use np.linspace to create 10 evenly spaced values between 0 and 1.

6) Inspection &rarr; For the arrays you created above, print their shape, size, ndim, and dtype.

7) Up for a challenge?
    - Create a 4D array with shape (2, 3, 2, 4) directly using np.array *(hint: you'll need to nest Python lists until it works)*.
    - Print its shape, size, and ndim
    - In one sentence, describe how you think of a 4D array.

***Ready? Go!***

In [ ]:
import numpy as np

In [ ]:
# 1. Create a 3D array with shape (2, 3, 4) filled with any numbers.

In [10]:
# 2. Create a 2D array of shape (4, 4) filled with zeros, 
# and a 2D array of shape (3, 5) filled with ones.

In [ ]:
# 3. Create a 3D array of shape (2, 2, 2) filled with the number 7.

In [ ]:
# 4. Use np.arange to generate a sequence from 5 to 30 with a step of 5.

In [11]:
# 5. Use np.linspace to create 10 evenly spaced values between 0 and 1.

In [ ]:
# 6. For the arrays you created above, print their shape, size, ndim, and dtype.

In [ ]:
# 7. Optional: Create a 4D array with shape (2, 3, 2, 4) directly using np.array

**SOLUTION**

***Pause here and try it yourself before scrolling down.***

In [12]:
# Answers may vary

import numpy as np

print("1) Multi-dimensional (3D)")
A3 = np.arange(24).reshape(2, 3, 4)   # any numbers; easy to see pattern
print(A3)
print("shape:", A3.shape, "size:", A3.size, "ndim:", A3.ndim)
print("-"*40)

print("2) Zeros and ones")
Z = np.zeros((4, 4))
O = np.ones((3, 5))
print("Zeros (4x4):\n", Z)
print("Ones  (3x5):\n", O)
print("-"*40)

print("3) Custom fill (3D 2x2x2 of 7)")
F = np.full((2, 2, 2), 7)
print(F)
print("-"*40)

print("4) Ranges with arange (5..30 step 5)")
R = np.arange(5, 31, 5)   # 5,10,15,20,25,30
print(R)
print("-"*40)

print("5) Even spacing with linspace (10 pts 0..1)")
L = np.linspace(0, 1, 10)
print(L)
print("-"*40)

print("6) Inspect each array")
arrays = {"A3": A3, "Z": Z, "O": O, "F": F, "R": R, "L": L}
# Loop instead of manually displaying each array inspection
for name, arr in arrays.items():
    print(f"{name}: shape={arr.shape}, size={arr.size}, ndim={arr.ndim}, dtype={arr.dtype}")
print("-"*40)


# Challenge Question
print("7) Challenge Question")

# Making a 4D array (2, 3, 2, 4)
# Putting multiple 3D blocks together creates a 4D structure
arr4d = np.array([
    [   # First block
        [[1, 2, 3, 4], [5, 6, 7, 8]],
        [[9, 10, 11, 12], [13, 14, 15, 16]],
        [[17, 18, 19, 20], [21, 22, 23, 24]]
    ],
    [   # Second block
        [[25, 26, 27, 28], [29, 30, 31, 32]],
        [[33, 34, 35, 36], [37, 38, 39, 40]],
        [[41, 42, 43, 44], [45, 46, 47, 48]]
    ]
])
print(arr4d)
print("Shape:", arr4d.shape)   # (2, 3, 2, 4)
print("Size:", arr4d.size)     # 48
print("Dimensions:", arr4d.ndim)  # 4


1) Multi-dimensional (3D)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
shape: (2, 3, 4) size: 24 ndim: 3
----------------------------------------
2) Zeros and ones
Zeros (4x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones  (3x5):
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
----------------------------------------
3) Custom fill (3D 2x2x2 of 7)
[[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]
----------------------------------------
4) Ranges with arange (5..30 step 5)
[ 5 10 15 20 25 30]
----------------------------------------
5) Even spacing with linspace (10 pts 0..1)
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
----------------------------------------
6) Inspect each array
A3: shape=(2, 3, 4), size=24, ndim=3, dtype=int64
Z: shape=(4, 4), size=16, ndim=2, dtype=float64
O: shape=(3, 5), size=15, ndim=2, dtype=float64
F: shape=(2, 2, 2), size

# Part 2: Indexing & Slicing

Indexing = Picking specific items/positions.

1D: arr[3] → the 4th item

2D: M[1, 2] → row 2, col 3 (0-based)

In [ ]:
arr = np.arange(10)          # [0 1 2 3 4 5 6 7 8 9]
arr[3]            # -> 3  (single index)
arr[[1, 4, 6]]    # -> [1 4 6] (fancy indexing, copy)
arr[arr % 2 == 0] # -> [0 2 4 6 8] (boolean mask, copy)

M = np.arange(12).reshape(3,4)
M[1, 2]          # element at row 1, col 2
M[:, 0]          # first column as a 1D view (shape (3,))

Slicing = Taking a range.
Syntax: start:stop:step (stop is excluded)
1D: arr[2:6] → items at positions 2,3,4,5
2D: M[0:2, 1:3] → rows 0–1 and cols 1–2
Shorthands: : = “all”, ::2 = every other, [::-1] = reverse

In [ ]:
arr = np.arange(10)
arr[2:7]     # -> [2 3 4 5 6]     (view)
arr[2:7:2]   # -> [2 4 6]         (view)
arr[::-1]    # -> reversed array  (view with negative stride)

M = np.arange(12).reshape(3,4)
M[0:2, 1:4]  # top-left 2x3 block (view)
M[:, :1]     # first column as 2D view (shape (3,1))

# Compare:
col_2d_view  = M[:, :1]    # view, shape (3,1)
col_2d_copy  = M[:, [0]]   # fancy indexing -> copy, shape (3,1)

# Part 3: Element-Wise Operations

### **What is an element-wise operation?**  


NumPy arrays are designed so that when you use standard math symbols (+, -, *, /, etc.), the operation is applied to each element individually, not to the array as a whole. **This is called element-wise operations.**

#### **Requirements:**
1) Arrays must have the **same shape**, or be ***broadcastable (explained later)***

In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print("Same shape:", a + b)   # [11 22 33]

2) Arrays must have **compatible data types** (NumPy will usually convert if needed).

In [ ]:
e = np.array([1, 2, 3])          # int
f = np.array([0.5, 1.5, 2.5])    # float
print("Dtype result:", e + f) # -> float result

3) For in-place operations like a += b, the **result must fit back into a’s dtype**.
4) The operation must make sense for that type (ex. can’t take np.sin of strings).

### Element-wise Examples:

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

# Arrays
print(a)
print(b)

# Addition
print("\nArray (a + b):\n",a + b)   # [11 22 33]

Explanation: NumPy is adding and multiplying each element above. 
By performing **a + b**, every element in **array a** is being added to the corresponding element in **array b**: `1 + 10`, `2 + 20`, `3 + 30`.

The same would apply if we performed any element-wise operation on an array, for example: **element-wise multiplication** on arrays a and b:

In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

# Arrays
print(a)
print(b)

# Multiplication
print("\nArray (a * b):\n",a * b)   # [10 40 90]

### **Exercise:** Element-Wise Operations

You’ve learned how NumPy can apply operations element by element across arrays. Now it’s your turn to practice without any starter code provided!

***Task:***
1. Create two 2D arrays `a` and `b` of the same shape. They should contain the following elemnts:
   - Array a &rarr; `[1, 2, 3, 4, 5, 6]`
   - Array b &rarr; `[10, 20, 30, 40, 50 , 60]`
2. Compute and print:
    - A + B (addition)
    - A - B (subtraction)
    - A * B (multiplication)
    - A / B (division)
    - A ** 2 (square each element of A)
3. Print the shape of both arrays.

In [15]:
import numpy as np

# Create two arrays
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[10, 20, 30],
              [40, 50, 60]])

# Element-wise operations
print("a + b =\n", a + b)       # element-wise addition
print("\na - b =\n", a - b)       # element-wise subtraction
print("\na * b =\n", a * b)       # element-wise multiplication
print("\na / b =\n", a / b)       # element-wise division
print("\na ** 2 =\n", a ** 2)     # element-wise power


a + b =
 [[11 22 33]
 [44 55 66]]

a - b =
 [[ -9 -18 -27]
 [-36 -45 -54]]

a * b =
 [[ 10  40  90]
 [160 250 360]]

a / b =
 [[0.1 0.1 0.1]
 [0.1 0.1 0.1]]

a ** 2 =
 [[ 1  4  9]
 [16 25 36]]


Did you guess correctly?
Play with the code! Change up the values in arrays a and b, rerun to see what new outputs you get.

# Part 4: Broadcasting

### **What is Broadcasting?**

In NumPy, **broadcasting is the set of rules that allow arrays of different shapes to work together in element-wise operations**.
Instead of manually reshaping or looping, NumPy automatically **“stretches”** smaller arrays so they can line up with bigger ones. This is called ***broadcasting***.

### **Scalars and Arrays**

*Reminder:* A **scalar** is just a single number. Whereas an **array** is a collection of numbers.

In [ ]:
x = 5        # integer scalar
y = 3.14     # float scalar

***NumPy allows you to mix scalars and arrays using broadcasting.***

Heres an example:

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = 10

print(a + b) # Scalar b is broadcast across every element of a

**Lets break this down:**
 - `a` has shape (2,3) &rarr; 2 rows, 3 columns.
 - `b` is just a scalar &rarr; shape().

Normally, if you tried to **add a list and a number in plain Python**, it would give you an **error**. *This is where NumPy comes into play :)*

Broadcasting works by **expanding smaller arrays** so their shapes match.
- A scalar has no dimensions, so NumPy "stretches it into the same shape as `a`

Essentially, it turns

In [ ]:
b = 10

Into:

Then performs element-wise addition:

Now Numpy has added each element of `a` with the corresponding `10`, the result becomes:

##### **Key takeaway:** 
When you add a scalar to an array, the scalar is broadcast across every element of the array. ***This saves you from writing loops or manually copying values.***

# Part 5: Reshaping vs Copying

#### When do operations return a **view** (no new data, shares memory) vs a **copy** (independent data)?  
If you understand views, shapes, and strides, you can avoid silent bugs and write faster code.

#### **Key terms**
- **View:** a new *array object* looking at the *same* memory. Changing the view changes the original.
- **Copy:** a new array *and* new memory. Changes do not affect the original.
- **Contiguous:** data stored without gaps. Most fresh arrays are **C-contiguous** (row-major). Fortran-contiguous is column-major.

#### 1) `reshape` tries to make a **view** (no copy) when possible

##### If the data buffer layout allows it, `reshape` returns a view. We can check with:
##### - `arr.base is other` (same base object?)
##### - `np.shares_memory(arr, other)`


In [ ]:
import numpy as np

x = np.arange(9)     # [0 1 2 3 4 5 6 7 8]
Y = x.reshape(3, 3)  # view if possible

print("Shares memory?", np.shares_memory(x, Y))
x[0] = 999
print("x:", x)
print("Y:\n", Y)     # Y changed too -> it's a view


#### 2) Use `.copy()` to **break** the link

##### If you want an independent array (safe to mutate), copy it.


In [ ]:
Z = Y.copy()
Y[0, 1] = -123
print("Y changed:\n", Y)
print("Z independent:\n", Z)  # unchanged
print("Shares memory?", np.shares_memory(Y, Z))
