# NumPy Tutorial
### Author: Ally Chen



## Description
### What is NumPy?
##### NumPy is Python's standard library for working with arrays. It supports working with arrays of N-dimensions, which is a principle of NumPy. Instead of looping in Python, NumPy lets you perform fast math on whole arrays at once, known as vectorized operations. Most data libraries (pandas, SciPy, scikit-learn, PyTorch) rely on NumPy under the hood.

## NumPy Installation
#### 1. Open a new terminal
#### 2. Ensure Python is installed:
#####  - Check using 'python --version' in terminal
### 3. In terminal run:
#### - macOS/Linux
##### python3 -m venv .venv
##### source .venv/bin/activate
##### python -m pip install --upgrade pip
##### pip install numpy
#### - Windows (PowerShell)
##### python -m venv .venv
##### .venv\Scripts\Activate
##### python -m pip install --upgrade pip
##### pip install numpy

## Verify Installation
#### Copy and paste the following code into your preferred code editor, and run it in the terminal to test if it is installed correctly.

In [21]:
# Import Numpy library
import numpy as np

# Print NumPy version number
print("NumPy:", np.__version__)

# Expected output: 25
print (np.array([3,4]).dot([3,4]))

NumPy: 2.3.2
25


# Part 1: Arrays

### Different Types of Arrays:
#### - `np.array([...])`: From a Python list
#### - `np.zeros(shape)` / `np.ones(shape)`: Filled arrays
#### - `np.arange(start, stop, step)`: Evenly spaced integers
#### - `np.linspace(start, stop, num)`: Evenly spaced floats (including the endpoint)

In [36]:
a = np.array([1, 2, 3])          # 1D array (vector)
b = np.zeros((2, 3))             # 2x3 of zeros (float by default)
c = np.ones(4, dtype=np.int32)   # 1D array of 4 ints
d = np.arange(0, 10, 2)          # 0,2,4,6,8
e = np.linspace(0, 1, 5)         # 0. ,0.25,0.5,0.75,1.

print("a:", a,"\n")
print("b:", b, "\nshape:", b.shape,"\n")
print("c:", c,"\n")
print("d:", d,"\n")
print("e:", e)

a: [1 2 3] 

b: [[0. 0. 0.]
 [0. 0. 0.]] 
shape: (2, 3) 

c: [1 1 1 1] 

d: [0 2 4 6 8] 

e: [0.   0.25 0.5  0.75 1.  ]


#### **What happened above?**
##### - `a` is a 1D array with 3 elements -> shape `(3,)`.
##### - `b` is a 2D array with 2 rows and 3 columns -> shape `(2, 3)`.
##### - `e` gave us 5 evenly spaced numbers **including** the endpoints 0 and 1.


### Inspecting Arrays

#### Topics:
##### - `.shape` = the size in each dimension (rows, cols, …)
##### - `.ndim` = number of dimensions (1D vector, 2D matrix, etc.)
##### - `.size` (total number of elements),
##### - `.dtype` = data type (e.g., `int64`, `float64`)

In [38]:
A = np.arange(12).reshape(3, 4)   # numbers 0..11 arranged as 3x4
print("Array (A):\n",A)
print("shape:", A.shape, "| ndim:", A.ndim, "| size:", A.size, "| dtype:", A.dtype)


Array (A):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape: (3, 4) | ndim: 2 | size: 12 | dtype: int64


##### **Why are 'Shapes' important?**
##### A shape tells you how many numbers you have and how they line up (rows, columns, ...). Most NumPy errors come from shape mismatches. They will come in especially handy when we learn about **broadcasting** later in the tutorial.

# Part 2: Reshaping vs Copying

#### When do operations return a **view** (no new data, shares memory) vs a **copy** (independent data)?  
##### If you understand views, shapes, and strides, you can avoid silent bugs and write faster code.

#### **Key terms**
##### - **View:** a new *array object* looking at the *same* memory. Changing the view changes the original.
##### - **Copy:** a new array *and* new memory. Changes do not affect the original.
##### - **Contiguous:** data stored without gaps. Most fresh arrays are **C-contiguous** (row-major). Fortran-contiguous is column-major.

#### 1) `reshape` tries to make a **view** (no copy) when possible

##### If the data buffer layout allows it, `reshape` returns a view. We can check with:
##### - `arr.base is other` (same base object?)
##### - `np.shares_memory(arr, other)`


In [41]:
import numpy as np

x = np.arange(9)     # [0 1 2 3 4 5 6 7 8]
Y = x.reshape(3, 3)  # view if possible

print("Shares memory?", np.shares_memory(x, Y))
x[0] = 999
print("x:", x)
print("Y:\n", Y)     # Y changed too -> it's a view


Shares memory? True
x: [999   1   2   3   4   5   6   7   8]
Y:
 [[999   1   2]
 [  3   4   5]
 [  6   7   8]]


#### 2) Use `.copy()` to **break** the link

##### If you want an independent array (safe to mutate), copy it.


In [44]:
Z = Y.copy()
Y[0, 1] = -123
print("Y changed:\n", Y)
print("Z independent:\n", Z)  # unchanged
print("Shares memory?", np.shares_memory(Y, Z))


Y changed:
 [[ 999 -123    2]
 [   3    4    5]
 [   6    7    8]]
Z independent:
 [[ 999 -123    2]
 [   3    4    5]
 [   6    7    8]]
Shares memory? False


# Part 3: Indexing & Slicing

#### Indexing = Picking specific items/positions.
##### 1D: arr[3] → the 4th item
##### 2D: M[1, 2] → row 2, col 3 (0-based)

In [47]:
import numpy as np
arr = np.arange(10)          # [0 1 2 3 4 5 6 7 8 9]
arr[3]            # -> 3  (single index)
arr[[1, 4, 6]]    # -> [1 4 6] (fancy indexing, copy)
arr[arr % 2 == 0] # -> [0 2 4 6 8] (boolean mask, copy)

M = np.arange(12).reshape(3,4)
M[1, 2]          # element at row 1, col 2
M[:, 0]          # first column as a 1D view (shape (3,))

array([0, 4, 8])

#### Slicing = Taking a range.
##### Syntax: start:stop:step (stop is excluded)
##### 1D: arr[2:6] → items at positions 2,3,4,5
##### 2D: M[0:2, 1:3] → rows 0–1 and cols 1–2
##### Shorthands: : = “all”, ::2 = every other, [::-1] = reverse

In [49]:
arr = np.arange(10)
arr[2:7]     # -> [2 3 4 5 6]     (view)
arr[2:7:2]   # -> [2 4 6]         (view)
arr[::-1]    # -> reversed array  (view with negative stride)

M = np.arange(12).reshape(3,4)
M[0:2, 1:4]  # top-left 2x3 block (view)
M[:, :1]     # first column as 2D view (shape (3,1))

# Compare:
col_2d_view  = M[:, :1]    # view, shape (3,1)
col_2d_copy  = M[:, [0]]   # fancy indexing -> copy, shape (3,1)