# NumPy Tutorial
Author: Ally Chen

This is an introductory tutorial for NumPy, the core Python library for fast numerical computing.

## What is NumPy?

NumPy provides high-performance, multidimensional arrays and vectorized operations that replace slow Python loops. Tools like pandas, SciPy, scikit-learn, and PyTorch, rely on NumPy under the hood. The result is **cleaner code that runs much faster with far less looping**. By the end of this tutorial, you’ll have the skills necessary to perform the following:
1. Represent data as vectors and matrices.
2. Create and inspect arrays.
3. Index and slice arrays.
4. Perform element-wise operations and broadcasting.
5. Reshape & copy data.

## NumPy Installation
1. Run the following cell. If it errors, install by running `pip install numpy` in your terminal. 

In [45]:
import numpy as np

## Multi-Dimensional Arrays

***Why multi-dimensional arrays for machine learning?***

Multi-dimensional arrays are the backbone of NumPy. Most real machine learning data isn’t flat. A single example might be a list of features numbers, a picture (a grid of pixels), or a short sequence over time, and we usually process **many** examples at once. A multi-dimensional array lets us keep each “direction” of the data separate (rows, columns, time, color channels, batch size) and run fast operations without Python loops

- A 1D array is like a simple list `[1, 2, 3]`.
- A 2D array is like a table or matrix (rows × columns).
- A 3D array is like a stack of tables.
- Higher dimensions are possible, but most people stop at 2D or 3D for practical work.

*NumPy arrays are called `ndarrays` (“n-dimensional arrays”) because they can have any number of dimensions.*
The more dimensions an array has, the trickier they are to understand. 

***When do you use 1D arrays?***

Use a 1D array when your data is one list of values, such as a single feature vector, a list of labels, or what a model is trying to predict. If you start stacking many of these together (many samples or many time steps), move up to 2D or higher so each axis has its own dimension.

In [46]:
 # 1D array/vector
x = np.array([5, 10, 15])
print(x)

[ 5 10 15]


***When do you use 2D arrays?***

Use a 2D array when your data naturally forms a table. In machine learning this is the standard “samples × features” layout: each row is one example and each column is one feature. A 2D array also works for single grayscale images (height × width) or any matrix you want to compute with. If you find yourself stacking many single vectors together, switch to a 2D array so rows and columns are explicit and easy to index.

In [47]:
# 2D array (matrix)
arr2 = np.array([[1, 2, 3],
              [4, 5, 6]])

# This is a 2D array, with 2 rows and 3 columns.
print(arr2) # (2, 3)

[[1 2 3]
 [4 5 6]]


***When do you use 3D arrays?***

Use a 3D array when there’s one more “direction” to keep track of, like color channels, time steps, or batches of 2D items. A single color image is naturally 3D (height × width × channels). Channels are the color components stored for each pixel. For an RGB image there are three channels, **R**ed, **G**reen, and **B**lue. A batch of grayscale images is also 3D (batch × height × width). Choosing 3D makes these axes explicit, which simplifies vectorized operations and avoids writing loops.

Think of a 3D array as a stack of 2D tables (matrices). Each table has rows and columns (2D), when you stack multiple tables on top of eachother, another dimension is added.

In [48]:
# A 3D array: 2 "tables", each with 3 rows and 4 columns.
arr3 = np.array([
    # Table 1
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]],

    # Table 2
    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])
print(arr3)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


## Common Arrays:
Instead of typing out every element individually by hand, an efficent feature of NumPy is that it can generate arrays for you. Here's some of the most common ones:
1. `np.array([...])`
2. **Constant arrays:**
   - `np.zeros()`
   - `np.ones()`
   - `np.full()`
3. `np.arange(start, stop, step)`
4.  `np.linspace(start, stop, num)`

#### **np.array()**
This array is from the Python list; we've seen this used previously when learning multi-dimensional arrays. Each pair of brackets `[...]` adds a new dimension. So a 1D list is a vector, a list of lists is a 2D matrix, a list of lists of lists is 3D, and so on.

`np.array()` can create arrays of any number of dimensions, depending on the structure of the input you give it. 

In [49]:
# 1D
a = np.array([1, 2, 3])

# 2D
b = np.array([[1, 2, 3],
              [4, 5, 6]])

# 3D
c = np.array([ [[1, 2], [3, 4]],
               [[5, 6], [7, 8]] ])

#### **Constant Arrays (zeros, ones, full)**
Constant arrays are super useful for quickly creating arrays filled with zeros or ones of any shape you want. When you prepare data or build simple baselines, you often need an array that starts at a known constant value, then you fill or update it later. NumPy makes this simple: use `np.zeros(shape)` to allocate an array of zeros; `np.ones(shape)` works the same way but fills with ones; and `np.full(shape, value)` lets you choose any constant. The API is identical across all three, only the fill value changes. In machine learning, these are handy for things like placeholder predictions, masks, padding, or bias columns.

***How do we create these arrays?***

The structure for this is `np.zeros(shape)`, where `shape` is the dimensions of the array you want NumPy to build. The same applies for `np.ones` and `np.full`.

In [50]:
# 1D array of 5 zeros
a = np.zeros(5) 

# 2D array (2 rows, 3 columns)
b = np.ones((2, 3))   

# 3D array (2 tables, 2 rows, 2 columns)
c = np.full((2, 2, 2), 7)

print("a:\n", a)
print("b:\n", b)
print("c:\n", c)

a:
 [0. 0. 0. 0. 0.]
b:
 [[1. 1. 1.]
 [1. 1. 1.]]
c:
 [[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]


#### **Exercise:** Creating Multi-Dimensional & Constant Number Arrays

Try it out by completing the following tasks.

**Task:**
1. Create a `5x5` array of all zeros.
2. Create a `2x3` array of all ones.
3. Create a `2x2x2` array filled with 5.
4. Create a 3D array with 2 layers, each layer is 2×3:

layer 0 → `[[100, 101, 102], [103, 104, 105]]`

layer 1 → `[[200, 201, 202], [203, 204, 205]]`

5. Print each array.

Use the starter code provided below:

In [51]:
# Starter Code

import numpy as np

# 1. Create a 5x5 array of zeros
a = ___
print("a:", a)

a: [[11, 12, 13], [14, 15, 16]]


In [52]:
# 2. Create a 4x3 array of ones
b = ___
print("b:", b)

b: [[11, 12, 13], [14, 15, 16]]


In [53]:
# 3. Create a 3x3x3 array filled with 5
c = ___
print("c:", c)

c: [[11, 12, 13], [14, 15, 16]]


In [54]:
# 4. 3D: 2 layers, each 2x3
a3 = __
print("3D:", a3)

3D: [[11, 12, 13], [14, 15, 16]]


**SOLUTION**

***Pause here and try it yourself before scrolling down.***

In [55]:
# 1.
a = np.zeros((5, 5))

# 2.
b = np.ones((4, 3))

# 3.
c = np.full((3, 3, 3), 5)

# 4.
a3 = np.array([
    [[100, 101, 102], [103, 104, 105]],
    [[200, 201, 202], [203, 204, 205]],
])

In [56]:
# 5.
print("a:", a)

a: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [57]:
print("b:", b)

b: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [58]:
print("c:", c)

c: [[[5 5 5]
  [5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]]]


In [59]:
print("3D:", a3)

3D: [[[100 101 102]
  [103 104 105]]

 [[200 201 202]
  [203 204 205]]]


#### **np.arange()**
Now lets move onto creating sequences!

`np.arange(start, stop, step)` creates values by stepping from start up to but not including stop. It’s most natural when you care about the step size, like “give me every 2nd number from 0 to 10,” which would be `np.arange(0, 10, 2)` → `0, 2, 4, 6, 8`. It’s great for integer sequences. With floating steps, tiny rounding errors can appear, so the last value may not land exactly where you expect. It’s the fastest way to make arrays of consecutive numbers or evenly spaced numbers without typing them out manually. They also work with any step size, you can make arrays that skip numbers (like evens, odds, multiples of 3, etc.) or even count backwards.

- `start` &rarr; where the sequence begins (default = 0).
- `stop` &rarr; where the sequence ends (no default).
- `step` &rarr; how much to increase each time (default = 1).

*Reminder:* Arrays start from 0, meaning the elements in the array will always be n-1.

In [60]:
# Sequence:
# 0 up to (but not including) 100.
a = np.arange(0, 100)  

# Sequence by any step size:
# Start = 0, stop = 15 (ends at 12), step = 3.
b = np.arange(0, 15, 3)  

# Counting down:
# De-increment by 1.
c = np.arange(5, -5, -1)

# Counting up by even numbers:
# Start = 2, end = 13 (ends at 12), step = 2.
d = np.arange(2, 13, 2)

print("a:", a)
print("b:", b)
print("c:", c)
print("d:", d)

a: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
b: [ 0  3  6  9 12]
c: [ 5  4  3  2  1  0 -1 -2 -3 -4]
d: [ 2  4  6  8 10 12]


#### **np.linspace()**

`np.linspace(start, stop, num)` creates exactly `num` evenly spaced values between start and stop. It’s the right choice when you care about how many points you get (for example, generating x-values for a plot), which is very common in math/engineering/CS when you need smooth ranges for graphs. 
- `start` &rarr; where the sequence begins (inclusive by default).
- `stop` &rarr; where the sequence ends (inclusive by default).
- `num` &rarr; how many pieces to generate (default = 50).

Then it gives you all the marks where it's split.

In [61]:
# Split the line from 0 to 10 into 5 equal parts
# This array starts at 0, stops at 10, and has 5 pieces.

arr = np.linspace(0, 10, 5)
print(arr)


[ 0.   2.5  5.   7.5 10. ]


***When should you use `.arange` vs `linspace`?***
- Use `.arange` when you know the **step size** you want.
- Use `.linspace` when you know the **number of points** you want.

## Inspecting Arrays

This section will look at the metadata of an array (not just the numbers inside it). That way, when working with bigger data later, you know how to read and deal with the information.

**When you create arrays, its important to know:**
- `.shape` &rarr; the size in each dimension (rows, cols, …)
- `.ndim` &rarr; number of dimensions (1D vector, 2D matrix, etc.)
- `.size` &rarr; total number of elements in array,
- `.dtype` &rarr; type of values inside the array (integers, floats, etc.)

***Why is `shape` important?***

When NumPy code doesn’t behave the way you expect, the first thing to check is the array’s `shape`. The shape attribute shows the structure of an array, meaning how many rows, columns, or higher dimensions it has. This is important because NumPy operations often require arrays to have matching or compatible shapes. Most NumPy errors come from shape mismatches.

In [62]:
import numpy as np

# 2 rows, 3 columns
arr2d = np.array([[1, 2, 3],
                [4, 5, 6]])
print("2D Shape:", arr2d.shape)   # (2, 3)

2D Shape: (2, 3)


**How do we read the shape of a 3D array?**

In [63]:
arr3d = np.array([
    [[ 1,  2,  3,  4],
     [ 5,  6,  7,  8],
     [ 9, 10, 11, 12]],

    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])
print("3D Shape:", arr3d.shape) # (2, 3, 4)

3D Shape: (2, 3, 4)


In this 3D array:
- 2 &rarr; shows the number of "tables" (or layers in the stack).
- 3 &rarr; shows the number of rows in each table.
- 4 &rarr; shows the number of columns in each table.

**Vector `(N,)` vs Column vector `(N, 1)`**

A 1D vector has shape `(N,)`; a column vector has shape `(N, 1)`. They print similarly but behave differently. The first has one axis; the second has two axes with one colum. This distinction matters for broadcasting and matrix-style math: adding a `(N,)` vector to a 2D matrix stretches across columns, while adding a `(N, 1)` column stretches down rows. Knowing which one you have prevents surprises in element-wise math and linear-algebra code.

***Why is `size` important?***

The `size` attribute tells you the total number of elements inside the array. This is useful for double-checking that you created the expected amount of data and for estimating how much memory the array might use.

In [64]:
# total of 6 elements
print(arr.size)   # 6

5


***Why is `ndim` important?***

The `ndim` attribute shows how many dimensions the array has. Knowing the number of dimensions helps you understand the structure of your data.

In [65]:
# this is a 2D array
print(arr.ndim)   # 2

1


***Why is `dtype` important?***

The `dtype` attribute tells you what kind of values are stored in the array, such as integers, floating-point numbers, or booleans. Names like `int8`, `int32`, `float32`, `float64` tell you how many bits are used per element. More bits &rarr; more memory per value, but a larger integer range or more decimal precision for floats. This matters because it determines the precision of calculations and whether certain operations can be carried out without errors. 

In [66]:
print(arr.dtype)   # int64

float64


## Indexing & Slicing

***Why is indexing useful?***

Indexing is important because real-world datasets are often very large. Being able to directly access one value, or a whole row, or column, at once without looping through the entire array makes NumPy code both faster and simpler. It also lets you pick out exactly the data you need from an array. Instead of working with the whole dataset, you can zoom in on specific values or smaller parts.

***How do we use indexing?***

In a 1D array, indexing works the same as a list:

In [67]:
import numpy as np
arr = np.array([10, 20, 30])
print(arr[0])  # gives 10
print(arr[2])  # gives 30

10
30


Now, let's look into how indexing works with multi-dimensional arrays:

In a 2D array you index with `arr[row, column]`: the first number moves **down** the rows and the second moves **across** the columns, with counting starting at 0. For the array below, `arr2d[1, 2]` selects row 1 then column 2, which is `6`.

In [68]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])
print(arr2d[0, 1])  # row 0, col 1: result = 2
print(arr2d[1, 2])  # row 1, col 2: result = 6


2
6


In 3D arrays you need three indices: `arr[table, row, column]`. Indexing 3D arrays is similar to indexing 2D arrays. The only difference is that we are now adding depth, or multiple tables. 

The first index picks which 2D slice (table) you’re on, the second moves down the rows within that table, and the third moves across the columns.

In [69]:
arr3d = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

# selects the first table’s first row and first column
print(arr3d[0, 0, 0]) # 1

# selects the first table’s second row and third column 
print(arr3d[0, 1, 2]) # 6

# picks the second table’s first row and second column 
print(arr3d[1, 0, 1]) # 8

# picks the second table’s second row and third column 
print(arr3d[1, 1, 2]) # 12

1
6
8
12


***What is Slicing?***

Slicing lets you take a **sub-array** along any dimension without writing loops. You use it to grab a row or column, select a window of features, crop an image patch, or split a dataset by ranges. It’s faster than looping in plain Python because NumPy does the work in optimized C.

The basic pattern is:
`array[start:stop:step]`
- start &rarr; where to begin (index number, default = 0)
- stop &rarr; where to end (but it does not include this index)
- step &rarr; how much to skip each time (default = 1)

**Let's look at how we apply this:**

In 1D, a slice is `a[start:stop:step]`. It returns a new view that walks from `start` up to but not including `stop`, jumping by `step`. This is the fastest way to take ranges or every n-th element without loops. Removing a value reverts it to that values default.

In [70]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])

# elements at indices 1,2,3,
print(a[1:4])     # [20 30 40]

# first 3 elements
print(a[:3])      # [10 20 30]

# every 2nd element
print(a[::2])     # [10 30 50]


[20 30 40]
[10 20 30]
[10 30 50]


In 2D, slicing uses two parts: `arr[row_slice, col_slice]`. The first piece chooses rows; the second piece chooses columns. A lone `:` means “take everything” along that axis. This lets you grab full rows or columns, crop a sub-table, or keep every other column with no loops required.

In [71]:
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# rows 0–1, columns 1–2
print(b[0:2, 1:3]) 
# [[2 3]
#  [5 6]]

# all rows, first column
print(b[:, 0])    # [1 4 7]

# entire second row 
print(b[1, :])    # [4 5 6]


[[2 3]
 [5 6]]
[1 4 7]
[4 5 6]


A 3D array adds one more axis; `arr[table_slice, row_slice, col_slice]`, where the first piece picks which 2D tables you want, the second piece picks rows inside those tables, and the third piece picks columns. The same `start:stop:step` rules apply, and `:` still means “take everything” on that axis.

In [72]:
c = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10,11,12]]
])

# both tables, first two rows, all columns
print(c[:, 0:2, :])

# first table, all rows, column 1 -> [2 5]
print(c[0, :, 1])     

# second table, all rows, first two columns
print(c[1, :, :2])    


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[2 5]
[[ 7  8]
 [10 11]]


#### **Exercise:** Indexing & Slicing 3D Arrays

Using the array provided below, complete the following tasks:

**Task**
1. Use indexing to get the element in the second table, second row, third column.
2. Use slicing to print the entire first table.
3. Use slicing to print the last row from each table.
4. Use slicing to print the second column from each table.
5. Combine indexing and slicing to print the last 2 rows and last 2 columns from both tables.

In [73]:
arr3d = np.array([
    [[ 1,  2,  3],
     [ 4,  5,  6],
     [ 7,  8,  9]],

    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]]
])

In [74]:
# 1. Use indexing to get the element in the second table, second row, third column.

In [75]:
# 2. Use slicing to print the entire first table.

In [76]:
# 3. Use slicing to print the last row from each table.

In [77]:
# 4. Use slicing to print the second column from each table.

In [78]:
# 5. Combine indexing and slicing to print the last 2 rows and last 2 columns from both tables.

**SOLUTION**

***Pause here and try it yourself before scrolling down.***

In [79]:
# 1. Specific element (table 1, row 1, col 2)
print("1.")
print(arr3d[1, 1, 2]) 

# 2. Entire first table
print("2.")
print(arr3d[0, :, :])

# 3. Last row from each table
print("3.")
print(arr3d[:, 2, :])

# 4. Second column from each table
print("4.")
print(arr3d[:, :, 1])

# 5. Last 2 rows and last 2 columns from both tables
print("5.")
print(arr3d[:, 1:3, 1:3])

1.
15
2.
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3.
[[ 7  8  9]
 [16 17 18]]
4.
[[ 2  5  8]
 [11 14 17]]
5.
[[[ 5  6]
  [ 8  9]]

 [[14 15]
  [17 18]]]


## Element-Wise Operations

***What is an element-wise operation?***


NumPy arrays are designed so that when you use standard math symbols (+, -, *, /, etc.), the operation is applied to each element individually, not to the array as a whole. **This is called element-wise operations.** Element-wise operation applies the same math to each matching position in two arrays. For this to work, the **shapes must be exactly the same** so NumPy can line up element with the element in the same position in the other array. *If your shapes don’t match, save that for the next part (broadcasting), where we’ll see how NumPy handles it without loops.*

***Element-wise Examples:***

In [80]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

# Arrays
print(a)
print(b)

# Addition
print("\nArray (a + b):\n",a + b)   # [11 22 33]

# Multiplication
print("\nArray (a * b):\n",a * b)   # [10 40 90]

[1 2 3]
[10 20 30]

Array (a + b):
 [11 22 33]

Array (a * b):
 [10 40 90]


**Explanation:** NumPy is adding and multiplying each element above. 
By performing `a + b`, every element in `a` is being added to the corresponding element in `b`: `1 + 10`, `2 + 20`, `3 + 30`. The same applies to multiplication.

#### **Exercise:** Element-Wise Operations

You’ve learned how NumPy can apply operations element by element across arrays. Now it’s your turn to practice, complete the following task below.

**Task:**
1. Create two 2D arrays `a` and `b` of the same shape.
2. Print the arrays above.
3. Compute and print all element-wise operations.

In [81]:
# 1. Create two 2D arrays `a` and `b` of the same shape. They should contain the following elements:
#   - Array a -> [[1, 2, 3],
#                  4, 5, 6]]
#   - Array b -> [[10, 20, 30]
#                  40, 50 , 60]]

In [82]:
# 2. Print the arrays above.

In [83]:
# 3. Compute and print all operations: +, -, *, /, and **2.

**SOLUTION**

***Pause here and try it yourself before scrolling down.***

In [84]:
import numpy as np

# Create two arrays
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[10, 20, 30],
              [40, 50, 60]])

# Print a & b
print("a:\n", a)
print("\nb:\n", b)

# Element-wise operations
print("\na + b =\n", a + b)       # element-wise addition
print("\na - b =\n", a - b)       # element-wise subtraction
print("\na * b =\n", a * b)       # element-wise multiplication
print("\na / b =\n", a / b)       # element-wise division
print("\na ** 2 =\n", a ** 2)     # element-wise power


a:
 [[1 2 3]
 [4 5 6]]

b:
 [[10 20 30]
 [40 50 60]]

a + b =
 [[11 22 33]
 [44 55 66]]

a - b =
 [[ -9 -18 -27]
 [-36 -45 -54]]

a * b =
 [[ 10  40  90]
 [160 250 360]]

a / b =
 [[0.1 0.1 0.1]
 [0.1 0.1 0.1]]

a ** 2 =
 [[ 1  4  9]
 [16 25 36]]


## Broadcasting

***What is Broadcasting?***

Broadcasting is how NumPy lets you write **loop-free, vectorized code** even when array shapes don’t exactly match. During an operation, NumPy can automatically **stretch** any dimension of size `1` (or a missing dimension in a 1D vector) so the shapes line up. **Broadcasting is the set of rules that allow arrays of different shapes to work together in element-wise operations**. Practically, this is why in **linear models** you can score an entire dataset in one expression; `y = X @ w + b`. Broadcasting repeats the bias `b` across all rows. More generally, it lets you add a bias vector to every row, scale/standardize columns, and combine arrays of compatible shapes, with no Python loops needed.

***What makes two dimensions compatible?***

Two dimensions are compatible if they are equal OR one of them is `1`. All dimensions must be compatible for the operation to proceed.

***Scalars + Arrays***

Normally, if you tried to **add a list and a number in plain Python**, it would give you an **error**. This is where NumPy comes into play.

NumPy allows you to mix scalars and arrays using broadcasting. A single number is broadcast to every element automatically.
- `a` has shape (2,3), `b` is just a scalar with shape( , ).

In [85]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = 10

print(a + b) # Scalar b is broadcast across every element of array a

[[11 12 13]
 [14 15 16]]


A scalar has no dimensions. Broadcasting works by **expanding smaller arrays** so their shapes match, so NumPy "stretches" the scalar into the same shape as `a`. *This saves you from writing loops or manually copying values.*

Essentially, it turns `b = 10` into:

In [86]:
[[10, 10, 10],
 [10, 10, 10]]

[[10, 10, 10], [10, 10, 10]]

Then performs element-wise addition:

In [87]:
[[1 + 10, 2 + 10, 3 + 10],
 [4 + 10, 5 + 10, 6 + 10]]

[[11, 12, 13], [14, 15, 16]]

Now Numpy has added each element of `a` with the corresponding `10`, the result becomes:

In [88]:
[[11, 12, 13],
 [14, 15, 16]]

[[11, 12, 13], [14, 15, 16]]

***Arrays + Arrays***

Next, let's look at broadcasting when dealing with only arrays.

Suppose we have:

**`(3,)` vs `(3, 1)`**

A row vector with shape `(3,)` matches the **columns** of `A`, so NumPy stretches it horizontally.  
A column vector with shape `(3, 1)` matches the **rows** of `A`, so NumPy stretches it vertically.  
This is why `(3,)` and `(3, 1)` behave differently even though they hold three numbers.

*Reminder: `(N,)` is a 1-D vector; when combined with an (row, col) array it lines up with the last dimension and broadcasts across rows. `(N, 1)` is a 2-D column; it matches the rows and broadcasts across columns.*

In [89]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])        # shape (3, 3)

row = np.array([10, 20, 30])      # shape (3,) -> stretches across columns
col = np.array([[100], [200], [300]])  # shape (3,1) -> stretches down rows

print("A shape:", A.shape, "| row shape:", row.shape, "| col shape:", col.shape)

print("\nA + row  (adds to each row across columns):\n", A + row)
print("\nA + col  (adds down rows):\n", A + col)


A shape: (3, 3) | row shape: (3,) | col shape: (3, 1)

A + row  (adds to each row across columns):
 [[11 22 33]
 [14 25 36]
 [17 28 39]]

A + col  (adds down rows):
 [[101 102 103]
 [204 205 206]
 [307 308 309]]


***How does this work?***

Broadcasting compares shapes right-to-left and two sizes are compatible if they are equal or `1`. Our matrix `A` is      `(3, 3)`. The vector row has shape `(3, )`, which NumPy treats like `(1, 3)`; the last dimension 3 matches, and the leading 1 is stretched down the 3 rows, so `row` is added to every row of `A`. The column `col` has shape `(3, 1)`; the first dimension 3 matches the rows, and the trailing `1` is stretched across the 3 columns, so `col` is added to every column. In both cases the result is (3, 3), as if row/col were expanded to full size, without writing loops. 

#### **Exercise:** Broadcasting

**Task**
1. Create a 5x5 array `a` of zeros.

3. Using arange(), add a row vector `b` containing elements 0-4 inclusive, to array `a`.

4. Multiply the new array `a` with a column vector `c`, containing elements 1-5 inclusive.

In [90]:
# 1. Create and print a 5x5 array `a` of zeros. 
print("Array a:", a)

Array a: [[1 2 3]
 [4 5 6]]


In [91]:
# 2. Using arange(), create row vector `b` containing elements 0-4 inclusive. Print the row vector.
print ("Row vector:", b)

Row vector: 10


In [92]:
# 3. Create column vector `c`, containing elements 1-5 inclusive. Print the column vector.
print ("Column vector:", c)

Column vector: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [93]:
# 4. Add array `a` and row vector `b`. Print the result.
print ("a + b:")

a + b:


In [94]:
# 5. Multiply array `a` by column vector `c`. Print the result.
print ("(a * b) + c:")

(a * b) + c:


**SOLUTION**

***Pause here and try it yourself before scrolling down.***

In [95]:
# 1. 5x5 array of zeros
a = np.zeros((5, 5))
print("Array a:", a)

# 2. row vector b = [0 1 2 3 4]
b = np.arange(5)
print ("Row vector:", b)

# 3. column vector c = [[1], [2], [3], [4], [5]]
c = np.array([[1],
              [2],
              [3],
              [4],
              [5]])
print ("Column vector:", c)

# 4. add row vector b
print("a + b:", a + b)

# 5. multiply by column vector c
print("(a + b) * c:", a * c)

Array a: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row vector: [0 1 2 3 4]
Column vector: [[1]
 [2]
 [3]
 [4]
 [5]]
a + b: [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
(a + b) * c: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## Reshaping & Copying

***What is Reshaping?***

Reshaping changes the shape (rows × columns × dimensions) of an array without changing the data inside. The total number of elements must stay the same.

Here's an example below:

In [96]:
arr = np.arange(1, 13)

print(arr)
 # [1, 2, ..., 12]

[ 1  2  3  4  5  6  7  8  9 10 11 12]


 - The original array has 12 elements.
 - Reshaping into `3, 4` means 3 rows x 4 columns = 12 elements.

In [97]:
reshaped = arr.reshape(3, 4)

print(reshaped)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


A handy feature NumPy offers is the use of `-1`. This saves you the hassle of having to do the math yourself, `-1` tells NumPy to figure out the dimension for you.
*You can only one `-1` at a time, or else NumPy won't know which dimension to calculate.*

In [98]:
# Case 1:
print(arr.reshape(3, -1))  # 3 rows, NumPy calculates columns

# Case 2:
print(arr.reshape(-1, 6))  # 6 columns, NumPy calculates rows


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


- In the first case: 12 / 3 = 4 &rarr; shape `(3, 4)`
- In the second case: 12 / 6 = 2 &rarr; shape `(2, 6)`

***What is Copying?***

In NumPy, when you assign one array to another variable, both variables point to the same data in memory. This means that if you change one variable, the other changes too. This is also known as a **view** or **reference**. To prevent this, we use `.copy()` for an independent array. This duplicates the data in memory, so changes in one array don’t affect the other.

In [99]:
a = np.array([1, 2, 3])
b = a        # not a real copy
c = a.copy() # real copy

b[0] = 99

# a and b share the same data, changing b also changes a.
print(a)  # [99  2  3]

# .copy() creates a completely independent array, changing c does not change a.
print(c)  # [1  2  3]


[99  2  3]
[1 2 3]


#### **Exercise:** Reshaping & Copying

**Task**
1. Create a `3×4` array `A` with the numbers 1–12. Print array `A`.
2. Reshape it into a new array `V` that is a view of the original.
   - Modify element `[0, 0] = 55` in the original.
4. Now make a copy `C` of the original array and reshape it.
   - Modify element `[0, 0] = 66` in the original.

In [100]:
# 1. Using arange() and reshape(), create a 3×4 array A with the numbers 1–12. Print array A.

In [101]:
# 2. Reshape it into a new array `V` that is a view of the original. Modify element `[0, 0] = 55` in the original, 
#    compare the two arrays and confirm whether they are still identical.

In [102]:
# 3. Make a real copy `C = A.reshape(2, 6).copy()`. Modify element `[0, 0] = 66` in the original, 
#    compare the two arrays and confirm whether they are still identical.

**SOLUTION**

***Pause here and try it yourself before scrolling down.***

In [103]:
# 1. create 3x4 array A
A = np.arange(1, 13).reshape(3, 4)
print("Original A:", A)

# 2. reshape into a view V
V = A.reshape(2, 6)

# modify element [0,0] in A
A[0, 0] = 55
print("After modifying A (view test):")
print("A:", A)
print("V:", V)   # V should also show the change (still identical to A’s data)

# 3. make a copy C of the original and reshape
C = A.reshape(2, 6).copy()

# modify element [0,0] in A again
A[0, 0] = 66
print("After re-modifying A (copy test):")
print("A:", A)
print("C:", C)   # C should NOT change


Original A: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
After modifying A (view test):
A: [[55  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
V: [[55  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
After re-modifying A (copy test):
A: [[66  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
C: [[55  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
