# PyTorch Tutorial

Author: Kellen Sullivan

This is an introductory tutorial for the deep learning library PyTorch. PyTorch gives professional developers the tools to create and train their own custom neural networks, and is the most commonly used deep learning framework in research and academia.

In this tutorial, you will be taught the fundamentals of PyTorch, through building your own neural network to classify hand-written digits. For this task, you will use the MNIST dataset, which is a collection of thousands of hand written digits with corresponding lables. Below is a sample of 4 hand-written digits from the dataset and their corresponding labels.


![MNISTDataSetExample](https://media.geeksforgeeks.org/wp-content/uploads/20240430155943/download-(39).png)



While you work through this tutorial and its exercises, its highly encouraged to check out the provided lecture videos created by math youtuber 3Blue1Brown. He explains the math behind the deep learning concepts this tutorial will breifly introduce, and his tutorials reference the exact same neural network that you will be building! His lessons are available to watch or read for free with the following link: [3Blue1Brown Neural Networks Lectures](https://www.3blue1brown.com/topics/neural-networks)





## Getting Started

To get started using PyTorch, you first have to install it! To do so, open a new terminal and run the following command:

- If you are on Windows/Mac: `pip3 install torch torchvision`
- If you are on Linux: `pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cpu`

Note that these commands will use your CPU as the compute platform. If you have an NVIDIA GPU, you can install PyTorch with CUDA as the compute platform to greatly speed up training. Check out the official installation guide to learn more: https://pytorch.org/get-started/locally/

You can confirm PyTorch was successfully installed by importing the package and printing out its version.

In [2]:
import torch

print(torch.__version__)

2.8.0+cpu


## Tensors

A tensor is an array or matrix like datastructure, similar to a NumPy array, but with extra capabalities that make it ideal for deep learning. Tensors may only contain numerical values, and are homogeneous meaning all elements in a tensor must be the same datatype.

### Initializing a Tensor

Pytorch provides many ways to intialize a new tensor. TODO: ADD MORE HERE

In [14]:
import numpy as np


# from a python list
t1 = torch.tensor([1,2,3])

# from a numpy array
np_arr = np.array([[1,2], [3,4]])
t2 = torch.from_numpy(np_arr)

print(f"Tensor from python list:\n{t1}\n")
print(f"Tensor from numpy array:\n{t2}\n")

Tensor from python list:
tensor([1, 2, 3])

Tensor from numpy array:
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)



You can also initialize a tensor using an existing tensor. The new tensor will have the same shape and datatype as the existing tensor.

In [ ]:
# from an existing tensor
t3 = torch.ones_like(t2)
t4 = torch.zeros_like(t2)
t5 = torch.rand_like(t2, dtype="float")

print(f"Tensor from t2 with all ones:\n{t3}\n")
print(f"Tensor from t2 with all zeros:\n{t4}\n")
print(f"Tensor from t2 with random values:\n{t5}")

Tensor from t2 with all ones:
tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

Tensor from t2 with all zeros:
tensor([[0, 0],
        [0, 0]], dtype=torch.int32)



### Attributes

Tensors have built in attributes that ... FILL OUT HERE. There are over 1000 attributes for Tensors that you can read about here: https://docs.pytorch.org/docs/stable/torch.html

### Operations



## Handling Data

The first step in creating a neural network is loading the data. Thankfully, PyTorch provides many tools to make loading and iterating through data simple!

### Datasets

Torchvision is library often used alongside PyTorch to support computer vision tasks. It also contains built-in datasets that can be easily loaded in and used to train neural networks in PyTorch, including the MNIST dataset that we will be training a model on!

To load in the MSNIST dataset, we must first import the datasets submodule from torchvision. We also import ToTensor from the transforms submodule which will be used to transform the handwritten digit images into PyTorch Tensors.

In [3]:
from torchvision import datasets
from torchvision.transforms import ToTensor

Now, we can use the following code to load in MNIST dataset.

q: why do we have to load training and testing data?
- when creating neural networks we want to train out network with part of the data, but then test it on never before seen data, to ensure it is indeed learning the desired behavior and not just memorizing the data.
q: what is the difference between each dataset?
- training dataset has 60k training images
- testing dataset has 10k testing images
q: what is the meaning behind each argument?
- `root` is the path where the train/test data is stored
- `train` specifies training or test dataset
- `download` if true, dowloads the data from the internet if it's not available at `root`.
- `transform` specify the feature and label transformations

In [4]:
training_data = datasets.MNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)

test_data = datasets.MNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor()
)

100%|██████████| 9.91M/9.91M [00:11<00:00, 871kB/s] 
100%|██████████| 28.9k/28.9k [00:00<00:00, 294kB/s]
100%|██████████| 1.65M/1.65M [00:02<00:00, 594kB/s]
100%|██████████| 4.54k/4.54k [00:00<?, ?B/s]


## Constructing a Neural Network

### Modules

### Activation Functions

### Init and Forward Function

## Loss Functions

## Optimizers

## Training and Using a Neural Network

## Save and Export a Model

## Conclusion and Further Readings